### ISSUE TITLE
Your README.md is wrong

### ISSUE THREAD

**Issue by bogdanm** [SmartArduino/WiFiMCU#1]
It says `Based on EMW3165 and Lua 5.1.4.`
It should say `Based on EMW3165 and eLua` (or even `Based on EMW3165, Lua 5.1.4. and eLua`), since you're clearly using the Lua core inside eLua. Give credit where credit is due.

**Comment by SmartArduino** [comment]
Thanks for your advise. It's true that we had used the elua code.
We have modifed the readme.md

**Comment by bogdanm** [comment]
Thanks for the quick reply and fix! :beer:
