### ISSUE TITLE
TCP Client functions broken in ver 0.9.8

### ISSUE THREAD

**Issue by lagnajeet** [SmartArduino/WiFiMCU#12]
net.new creates a thread which it fails to close even after the actual socket is closed itself. So if there is a function as below

```
function test_sock()
    conn=net.new(net.TCP,net.CLIENT)
    net.on(conn,"receive", function(conn, payload)
                            print(payload)
                            net.close(conn)
                           end)
    net.on(conn,"connect", function(conn, payload)
                            net.send(conn,"sent data")
                           end) 
    net.start(conn,81, "192.168.0.5")                          
end
```

 It works only the first time the function is called and in the subsequent times nothing happens. As shown in the picture below 
![image](https://cloud.githubusercontent.com/assets/8535629/12670846/7a0ac8bc-c620-11e5-88df-0bd95973b261.png)

I found a solution for this problem by changing the function  _thread_net in the file net.c as shown below

```
static void _thread_net(void *inContext)
{
  (void)inContext;
  while(1)
  {
    if(!_thread_net_handle()) break;
    mico_thread_msleep(1);
  }

  net_thread_is_started =  false;  //Move the line to top
  mico_rtos_delete_thread( NULL );
 // net_thread_is_started =  false;
}
```

My theory of operation is the thread was getting deleted before it can set the value of net_thread_is_started =  false

Please update the code if possible.
Thanks
LP

**Comment by SmartArduino** [comment]
Thank you, We may update the code next version.
