### ISSUE TITLE
dofile inside timer function

### ISSUE THREAD

**Issue by Triade1** [SmartArduino/WiFiMCU#4]
Hello, 

When I execute dofile() inside a timer function the system reboot...

function startup()
    print('in startup...')
    tmr.stop(0)
    dofile("main.lua")
end

print("*\* 5 second pause before startup **")
tmr.start(0,5000,startup)

When I call startup function directly, dofile() works fine.

**Comment by SmartArduino** [comment]
Hi, Triade1
We have confirmed this bug, and tring to repair it in the next version. 
Thanks a lot.

**Comment by Triade1** [comment]
Hello,

Is solved this bug in the firmware version 0.9.6?

Thanks!
