### ISSUE TITLE
wifi.powersafe() and Hostname

### ISSUE THREAD

**Issue by sn2k** [SmartArduino/WiFiMCU#7]
The wifi.powersafe() 
funktion is a bug:

0_func_wifi.lua:17: attempt to call field 'powersafe' (a nil value)

Another small problem i can't change the Hostname for Wifimcu it's always "MXCHIP"

**Comment by SmartArduino** [comment]
It's powersave, not powersafe.
The hostname can not be changed in present firmware.

**Comment by sn2k** [comment]
The Right command is:
wifi.powersave(true)

Powersave off:
40mA IDLE   (0.2Watt)
90mA if Wifi and connected to ap ever (0.44Watt)
130mA on send over Wifi (0.65Watt)

Powersafe on:
40mA IDLE
90mA if Wifi on and connected to ap
30mA if Wifi in powersafe Modus
30mA-70mA if a Programm run, not costant it ever change on cpu usage
130mA on send over Wifi
